import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import { dataDir } from "@/lib/config/env";

const uploadsDir = join(dataDir(), "uploads");

export interface DocumentSeed {
  id: string;
  taskId: string;
  projectId: string;
  filename: string;
  originalName: string;
  mimeType: string;
  size: number;
  storagePath: string;
  direction: "input" | "output";
  category: string | null;
  status: "uploaded";
  createdAt: Date;
  updatedAt: Date;
}

interface DocumentDef {
  originalName: string;
  projectIndex: number;
  taskIndex: number;
  direction: "input" | "output";
  category: string | null;
  content: string;
}

// --- All documents are markdown (.md) for simplicity and readability ---

const DOCUMENTS: DocumentDef[] = [
  // ── P1: Product Launch (2 input, 2 output) ────────────────────────
  {
    originalName: "launch-brief.md",
    projectIndex: 0,
    taskIndex: 0,
    direction: "input",
    category: "brief",
    content: `# AI Copilot v2 Launch Brief

## Product
AI Copilot v2 — multi-agent orchestration platform for business operations.
52+ agent profiles, 25 workflow patterns, 5 AI runtimes.

## Target Audience
- **Primary:** Solo founders running AI-assisted businesses
- **Secondary:** Agency owners managing multi-client AI operations
- **Tertiary:** PE operating partners standardizing portfolio AI

## Positioning
- **Tagline:** "Your Business, Run by AI"
- **Category:** AI Agent Orchestration Platform
- **Differentiator:** The missing layer between "run an agent" and "run my business"

## Launch Channels
1. Product Hunt (Day 1 — Tuesday)
2. Email sequence (3-touch, Day 0/3/7)
3. LinkedIn thought leadership (5-post series)
4. Twitter/X launch thread
5. Blog: "Why Your Business Needs an AI Operations Layer"

## Success Metrics
| Metric | Target |
|--------|--------|
| Signups (7 days) | 500 |
| Product Hunt upvotes | 50 |
| Press mentions | 3 |
| Email-to-trial conversion | 10% |

## Timeline
- **Week -2:** Copy + landing page
- **Week -1:** A/B tests + social calendar
- **Week 0:** Launch day
- **Week +1:** Follow-up sequence + retargeting
`,
  },
  {
    originalName: "competitor-analysis.md",
    projectIndex: 0,
    taskIndex: 0,
    direction: "input",
    category: "research",
    content: `# AI Copilot Competitive Analysis

## 1. Cursor
- **Positioning:** "The AI Code Editor"
- **Pricing:** $20/mo (Pro), $40/mo (Business)
- **Strengths:** IDE-native, fast autocomplete, good UX
- **Weaknesses:** Code-only, no orchestration, no governance

## 2. Windsurf (Codeium)
- **Positioning:** "The first agentic IDE"
- **Pricing:** Free tier, $15/mo (Pro)
- **Strengths:** Multi-file editing, strong free tier
- **Weaknesses:** Developer-only, no business operations

## 3. GitHub Copilot
- **Positioning:** "Your AI pair programmer"
- **Pricing:** $10/mo (Individual), $19/seat (Business)
- **Strengths:** Massive distribution (GitHub), brand trust
- **Weaknesses:** Single-agent, no workflows, limited tools

## 4. Tabnine
- **Positioning:** "AI that works where you work"
- **Pricing:** $12/mo (Pro), enterprise pricing
- **Strengths:** Privacy-focused, on-prem option
- **Weaknesses:** Autocomplete-only, no agentic capabilities

## 5. Sourcegraph Cody
- **Positioning:** "AI coding assistant with codebase context"
- **Pricing:** Free tier, $9/seat (Pro)
- **Strengths:** Codebase understanding, search integration
- **Weaknesses:** Read-heavy, limited write operations

## Key Gap
None of the 5 address multi-agent orchestration, governance, or business operations beyond code. ainative's positioning as "business operations" is **uncontested**.
`,
  },
  {
    originalName: "launch-campaign-plan.md",
    projectIndex: 0,
    taskIndex: 1,
    direction: "output",
    category: "report",
    content: `# AI Copilot v2 — Launch Campaign Plan
*Generated by GTM Launch Strategist Agent*

## Executive Summary
Multi-channel launch targeting solo founders and agency owners. 3 headline variants tested, email sequence drafted, social calendar set.

## Headline Variants
| Variant | Headline | Angle |
|---------|----------|-------|
| A | "Your Business, Run by AI" | Orchestration-led |
| B | "Stop Stitching — Start Orchestrating" | Pain-led |
| C | "52 Agents. One Command Center." | Scale-led |

## Email Sequence
- **Day 0:** Launch announcement + quick start
- **Day 3:** Feature deep-dive (workflows + governance)
- **Day 7:** Case study — "How a solo founder runs 3 businesses with ainative"

## Social Calendar
- **Week 1:** LinkedIn series (5 posts, MWF) + Twitter launch thread (Day 1)
- **Week 2:** Community engagement + retargeting

## Recommendation
A/B test Variant A vs B. Orchestration messaging resonates with ops buyers. Pain-led converts better on cold traffic. Test with 50/50 split, 7-day window.
`,
  },
  {
    originalName: "social-media-calendar.md",
    projectIndex: 0,
    taskIndex: 5,
    direction: "output",
    category: "template",
    content: `# AI Copilot v2 — Social Media Launch Calendar

## Week 1
| Day | Channel | Content | Target |
|-----|---------|---------|--------|
| Mon | LinkedIn | "Why your AI agents need a manager" (narrative hook) | 1,200 impressions |
| Tue | Twitter | Launch thread (8 tweets, product screenshots, founder story) | 5,000 impressions |
| Wed | LinkedIn | "The governance gap in agentic AI" (problem framing, tag 3 voices) | 1,500 impressions |
| Fri | LinkedIn | "3 patterns for multi-agent workflows" (tactical, include diagram) | 1,800 impressions |

## Week 2
| Day | Channel | Content | Target |
|-----|---------|---------|--------|
| Mon | LinkedIn | "Local-first AI — why it matters" (contrarian take) | 1,200 impressions |
| Wed | LinkedIn | "We gave 52 agents one command center" (product reveal) | 2,000 impressions |
| Fri | All | Community recap + user highlights | 1,000 impressions |
`,
  },

  // ── P2: Content Engine (2 input, 1 output) ────────────────────────
  {
    originalName: "seo-keyword-research.md",
    projectIndex: 1,
    taskIndex: 6,
    direction: "input",
    category: "research",
    content: `# SEO Keyword Research — AI Agent Orchestration Cluster

| Keyword | Monthly Volume | Difficulty | CPC | SERP Features | Content Gap |
|---------|---------------|------------|-----|---------------|-------------|
| AI agent orchestration | 2,400 | 38 | $4.20 | Featured Snippet | No comprehensive guide |
| multi-agent framework | 1,800 | 42 | $3.80 | People Also Ask | Comparison missing |
| AI agent platform | 4,200 | 55 | $6.50 | Ads + Featured | Dominated by LangChain |
| agentic AI tools | 3,100 | 35 | $5.10 | People Also Ask | No tools roundup |
| AI workflow automation | 5,600 | 48 | $7.20 | Featured Snippet | Enterprise-focused only |
| agent governance AI | 890 | 22 | $3.40 | None | Zero coverage |
| AI operations platform | 1,200 | 30 | $4.80 | Ads | SaaS angle missing |
| multi-runtime AI | 340 | 15 | $2.90 | None | Zero coverage |
| AI agent scheduling | 720 | 28 | $3.20 | People Also Ask | Cron-focused only |
| heartbeat monitoring AI | 180 | 12 | $2.10 | None | Zero coverage |

## Top Opportunity
"AI agent orchestration" — medium difficulty, no comprehensive guide exists. Target position 1-3 with a pillar page.
`,
  },
  {
    originalName: "editorial-calendar.md",
    projectIndex: 1,
    taskIndex: 7,
    direction: "input",
    category: "template",
    content: `# Editorial Calendar — Q2 2026

| Week | Topic | Primary Keyword | Target Words | Status | Publish Date |
|------|-------|----------------|-------------|--------|--------------|
| W14 | AI Agent Orchestration Guide | AI agent orchestration | 1,800 | Published | 2026-03-28 |
| W15 | Multi-Agent Workflows Explained | multi-agent framework | 1,500 | In Progress | 2026-04-04 |
| W16 | Governance for Agentic AI | agent governance AI | 1,600 | Outlined | 2026-04-11 |
| W17 | AI Ops for Solo Founders | AI operations platform | 1,400 | Planned | 2026-04-18 |
| W18 | Heartbeat Scheduling Deep Dive | heartbeat monitoring AI | 1,200 | Planned | 2026-04-25 |
| W19 | Multi-Runtime Architecture | multi-runtime AI | 1,800 | Planned | 2026-05-02 |
| W20 | AI Agent Tools Roundup 2026 | agentic AI tools | 2,000 | Planned | 2026-05-09 |

## Distribution Plan
Each article gets: LinkedIn post (same day), newsletter feature, Twitter thread, Dev.to cross-post (3 days later for technical pieces).
`,
  },
  {
    originalName: "weekly-content-report.md",
    projectIndex: 1,
    taskIndex: 7,
    direction: "output",
    category: "report",
    content: `# Weekly Content Performance Report — W14
*Generated by Content Production Editor Agent*

## Published This Week
**"AI Agent Orchestration Guide"** — 1,920 words, published Mar 28
- Organic sessions: 342 (first 5 days)
- Avg time on page: 4:12
- Backlinks acquired: 2 (DevOps Weekly, AI Newsletter)

## SEO Performance
- Target keyword: "AI agent orchestration" — currently **position 14**
- Expected to reach page 1 within 3 weeks
- Secondary keywords indexed: 4 of 6

## Distribution Metrics
| Channel | Metric | Value |
|---------|--------|-------|
| LinkedIn | Impressions | 1,240 |
| LinkedIn | Engagements | 89 (7.2% rate) |
| Newsletter | Open rate | 28% |
| Newsletter | CTR | 4.2% |
| Twitter thread | Impressions | 3,400 |

## Next Week
- **Topic:** "Multi-Agent Workflows Explained"
- **Status:** Outline approved, draft in progress
- **Distribution:** LinkedIn + newsletter + Dev.to cross-post
`,
  },

  // ── P3: Customer Success (2 input, 1 output) ─────────────────────
  {
    originalName: "customer-feedback-export.md",
    projectIndex: 2,
    taskIndex: 13,
    direction: "input",
    category: "data",
    content: `# Customer Health Data Export — Q1 2026

| Account | Plan | MRR | NPS Score | Last Login | Support Tickets | Health |
|---------|------|-----|-----------|------------|----------------|--------|
| Acme Corp | Team | $499 | 72 | 2026-04-02 | 1 | Green |
| DataFlow AI | Pro | $149 | 45 | 2026-03-28 | 3 | Yellow |
| ScaleUp HQ | Team | $499 | 81 | 2026-04-01 | 0 | Green |
| BrightPath | Pro | $149 | 28 | 2026-03-15 | 5 | Red |
| CloudBase | Pro | $149 | 65 | 2026-04-01 | 2 | Green |
| NexaPay | Team | $499 | 38 | 2026-03-20 | 4 | Yellow |
| QuickShip | Pro | $149 | 55 | 2026-03-30 | 1 | Green |
| TechStart | Community | $0 | 22 | 2026-02-28 | 6 | Red |
| GreenGrid | Pro | $149 | 70 | 2026-04-02 | 0 | Green |
| Meridian Corp | Team | $499 | 42 | 2026-03-25 | 3 | Yellow |

## Summary
- **Green:** 5 accounts (50%) — healthy engagement
- **Yellow:** 3 accounts (30%) — watch closely
- **Red:** 2 accounts (20%) — immediate intervention needed
`,
  },
  {
    originalName: "onboarding-playbook.md",
    projectIndex: 2,
    taskIndex: 12,
    direction: "input",
    category: "brief",
    content: `# Customer Onboarding Playbook

## Day 0: Welcome + Quick Start
- Send welcome email with getting started guide
- Trigger in-app checklist: create project, run first agent, set up workflow
- Segment by plan tier (Community/Pro/Team)

## Day 2: Feature Spotlight
- Email: "Your first agent in 5 minutes" walkthrough
- Link to video tutorial (2 min)
- CTA: Run your first workflow

## Day 5: Check-In
- Email: "How are things going?"
- Direct reply CTA — route to CS team
- **If no project created:** trigger CSM outreach

## Day 14: Health Check
- Automated assessment: login frequency, feature adoption, support tickets
- Score: Green (active), Yellow (partial), Red (at-risk)
- **Red accounts:** immediate CSM call + personalized rescue plan

## Success Metrics
| Metric | Target |
|--------|--------|
| Day 7 activation rate | 65% |
| Day 30 retention | 80% |
| NPS at Day 30 | 50+ |
`,
  },
  {
    originalName: "churn-risk-report.md",
    projectIndex: 2,
    taskIndex: 13,
    direction: "output",
    category: "report",
    content: `# Churn Risk Report — Q1 Cohort
*Generated by Customer Success Analyst Agent*

| Account | Risk Score | Primary Signal | Days Since Login | Open Tickets | NPS Trend | Intervention |
|---------|-----------|----------------|-----------------|-------------|-----------|--------------|
| BrightPath | 92 | Low usage + high tickets | 19 | 5 | Declining (-15) | Schedule CSM call — offer training session |
| TechStart | 88 | No login in 34 days | 34 | 6 | N/A (no response) | Executive outreach — potential churn |
| NexaPay | 65 | NPS drop + stalled onboarding | 14 | 4 | Declining (-8) | Feature walkthrough — focus on workflows |
| DataFlow AI | 45 | Moderate tickets | 6 | 3 | Stable | Monitor — send check-in email |
| Meridian Corp | 40 | NPS dip | 9 | 3 | Slight decline (-3) | Proactive NPS follow-up |

## Key Finding
Accounts without a workflow created by Day 7 have an **82% churn correlation**. Recommend triggering proactive intervention at Day 5.
`,
  },

  // ── P4: TechVenture Partners (2 input, 2 output) ─────────────────
  {
    originalName: "financial-statements.md",
    projectIndex: 3,
    taskIndex: 18,
    direction: "input",
    category: "data",
    content: `# HealthSync Financial Summary — 9 Quarters

| Metric | 2024 Q1 | 2024 Q2 | 2024 Q3 | 2024 Q4 | 2025 Q1 | 2025 Q2 | 2025 Q3 | 2025 Q4 | 2026 Q1 |
|--------|---------|---------|---------|---------|---------|---------|---------|---------|---------|
| ARR ($M) | 3.2 | 3.8 | 4.5 | 5.2 | 5.8 | 6.4 | 7.1 | 7.8 | 8.2 |
| MRR ($K) | 267 | 317 | 375 | 433 | 483 | 533 | 592 | 650 | 683 |
| Gross Margin (%) | 74 | 75 | 76 | 77 | 78 | 78 | 78 | 78 | 78 |
| Net Retention (%) | 108 | 110 | 112 | 115 | 116 | 117 | 118 | 118 | 118 |
| Burn Rate ($K/mo) | 420 | 410 | 400 | 395 | 390 | 385 | 380 | 380 | 380 |
| Runway (months) | 22 | 20 | 18 | 17 | 16 | 15 | 14 | 14 | 14 |
| Customer Count | 42 | 51 | 63 | 78 | 89 | 102 | 115 | 128 | 138 |
| Avg Contract Value ($K) | 76 | 75 | 71 | 67 | 65 | 63 | 62 | 61 | 59 |
`,
  },
  {
    originalName: "market-sizing.md",
    projectIndex: 3,
    taskIndex: 19,
    direction: "input",
    category: "research",
    content: `# Healthcare Scheduling Market Analysis

## Total Addressable Market (TAM)
**US healthcare scheduling software: $12.4B (2026)**

Growth drivers:
- Labor shortages forcing efficiency
- Patient no-show costs ($150B annually)
- Telehealth integration demand

## Serviceable Addressable Market (SAM)
**AI-enabled scheduling, mid-market (10-200 providers): $3.8B**

Key requirements: intelligent scheduling, no-show prediction, multi-provider coordination, EHR integration

## Serviceable Obtainable Market (SOM)
**Outpatient clinics in top 20 metros: $420M**

Why: concentrated provider networks, highest no-show rates, most receptive to AI (34% have AI budget allocated)

## Competitive Landscape
1. **Zocdoc** — consumer-facing, not AI-native
2. **Phreesia** — check-in focused, scheduling is secondary
3. **QGenda** — physician scheduling, not patient-facing
4. **Clockwise Health** — early stage, limited features

**None have true AI-powered scheduling optimization. Greenfield for an AI-native entrant like HealthSync.**
`,
  },
  {
    originalName: "due-diligence-memo.md",
    projectIndex: 3,
    taskIndex: 20,
    direction: "output",
    category: "report",
    content: `# HealthSync Due Diligence Memo
*Prepared by Portfolio Due Diligence Analyst Agent*

## Executive Summary
HealthSync is a category-defining AI scheduling platform targeting mid-market outpatient practices. The company demonstrates strong product-market fit with 118% net retention and 42% ARR growth.

## Investment Thesis
1. **AI-native product** with proven 35% no-show reduction
2. **Net retention 118%** signals expansion revenue
3. **Greenfield competitive landscape** — no AI-native incumbents
4. **$3.8B SAM** growing at 24% CAGR

## Financial Highlights
| Metric | Value |
|--------|-------|
| ARR | $8.2M (42% YoY growth) |
| Gross margin | 78% |
| Net retention | 118% |
| Burn rate | $380K/mo |
| Runway | 14 months |
| LTV/CAC | 4.2x (payback 11 months) |

## Top Risks
1. **Customer concentration:** top 5 accounts = 62% of ARR
   - *Mitigant:* Logo diversification plan targets 20 new logos in 12 months
2. **Single-product risk:** scheduling only
   - *Mitigant:* Waitlist management and patient engagement on roadmap
3. **Regulatory:** HIPAA compliance complexity for new markets
   - *Mitigant:* SOC 2 Type II certified, HIPAA BAA standard

## Recommendation: **GO**
Invest at current $45M valuation ($5.5x ARR). Condition: Secure 3 new enterprise logos within 6 months.
`,
  },
  {
    originalName: "board-deck.md",
    projectIndex: 3,
    taskIndex: 21,
    direction: "output",
    category: "report",
    content: `# TechVenture Partners — Q2 Portfolio Review

## Portfolio Overview
4 companies, $28M combined ARR, 38% weighted growth

## Company Summaries

### HealthSync
- **ARR:** $8.2M (+42%) | **GM:** 78% | **NRR:** 118%
- **Status:** GO recommendation, DD complete
- **Action:** Close investment at $45M valuation

### NovaPay
- **ARR:** $12.1M (+35%) | **GM:** 72% | **NRR:** 112%
- **Status:** Stable, watching burn rate acceleration
- **Action:** CFO search in progress

### DataBridge
- **ARR:** $5.4M (+48%) | **GM:** 68% | **NRR:** 125%
- **Status:** Fastest growth, needs sales capacity
- **Action:** Series A prep — target Q3 raise

### CloudSecure
- **ARR:** $2.3M (+28%) | **GM:** 82% | **NRR:** 108%
- **Status:** Early but promising unit economics
- **Action:** Continue monitoring, next board review Q3

## Key Actions
1. Close HealthSync investment
2. NovaPay CFO search
3. DataBridge Series A prep

## Risk Watch
- NovaPay burn acceleration
- DataBridge single-threaded sales
`,
  },

  // ── P5: GreenLeaf Commerce (1 input) ──────────────────────────────
  {
    originalName: "product-catalog.md",
    projectIndex: 4,
    taskIndex: 24,
    direction: "input",
    category: "data",
    content: `# GreenLeaf Commerce — Product Catalog (Top 10 SKUs)

| SKU | Product Name | Category | Price | Reviews | Rating | Monthly Searches | Listing Score |
|-----|-------------|----------|-------|---------|--------|-----------------|---------------|
| SKU-1042 | Bamboo Kitchen Set | Kitchen | $49.99 | 342 | 4.2 | 2,800 | 52 |
| SKU-1108 | Organic Cotton Sheets | Bedding | $89.99 | 1,205 | 4.6 | 4,200 | 71 |
| SKU-1215 | Recycled Glass Vases | Decor | $34.99 | 187 | 4.1 | 1,100 | 48 |
| SKU-1301 | Eco Yoga Mat | Fitness | $59.99 | 892 | 4.5 | 3,400 | 68 |
| SKU-1422 | Reusable Beeswax Wraps | Kitchen | $24.99 | 2,341 | 4.7 | 5,100 | 82 |
| SKU-1503 | Solar Garden Lights | Outdoor | $39.99 | 567 | 4.3 | 2,200 | 61 |
| SKU-1618 | Bamboo Toothbrush Set | Personal | $12.99 | 3,102 | 4.4 | 6,800 | 75 |
| SKU-1722 | Recycled Tote Bags | Accessories | $19.99 | 1,456 | 4.5 | 3,900 | 73 |
| SKU-1834 | Organic Face Serum | Beauty | $44.99 | 723 | 4.1 | 2,600 | 55 |
| SKU-1901 | Compostable Phone Case | Accessories | $29.99 | 445 | 3.9 | 1,800 | 44 |

## Optimization Priority
Top opportunity: **Bamboo Kitchen Set (SKU-1042)** — 2.8K monthly searches but title misses primary keyword entirely. Listing score 52/100.
`,
  },

  // ── P7: Revenue Operations (1 input, 1 output) ────────────────────
  {
    originalName: "pipeline-snapshot.md",
    projectIndex: 6,
    taskIndex: 36,
    direction: "input",
    category: "data",
    content: `# Pipeline Snapshot — Week of March 31, 2026

| Deal Name | Owner | Stage | Amount | Days in Stage | Close Date | Next Step | Risk |
|-----------|-------|-------|--------|--------------|------------|-----------|------|
| Acme Corp Expansion | Sarah K | Negotiation | $180K | 3 | 2026-04-15 | Contract review | Low |
| Atlas Financial | Mike R | Evaluation | $95K | 8 | 2026-04-30 | Demo follow-up | Medium |
| Meridian Corp | Sarah K | Proposal | $220K | 12 | 2026-05-10 | VP meeting needed | High |
| Pinnacle Tech | Jordan L | Evaluation | $65K | 15 | 2026-05-30 | Re-qualify | High |
| DataPulse | Mike R | Discovery | $45K | 2 | 2026-06-15 | Discovery call #2 | Low |
| NexaHealth | Jordan L | Proposal | $150K | 5 | 2026-04-25 | Pricing discussion | Medium |
| CloudFirst | Sarah K | Negotiation | $310K | 1 | 2026-04-10 | MSA redline | Low |
| GreenTech Solutions | Mike R | Discovery | $75K | 4 | 2026-06-30 | Needs analysis | Low |
| Summit Partners | Jordan L | Evaluation | $120K | 7 | 2026-05-15 | Technical review | Medium |
| Vertex Labs | Sarah K | Discovery | $55K | 1 | 2026-07-15 | Intro meeting | Low |

## Summary
- **Active deals:** 10 | **Total weighted:** $2.8M
- **Net new this week:** +3 deals ($175K)
- **Stalled (>5 days):** 3 deals (Meridian, Pinnacle, Atlas)
`,
  },
  {
    originalName: "weekly-deal-review.md",
    projectIndex: 6,
    taskIndex: 37,
    direction: "output",
    category: "report",
    content: `# Weekly Deal Review — Revenue Operations
*Generated by Revenue Operations Analyst Agent*

## Pipeline Summary
- **Active deals:** 10 | **Total weighted:** $2.8M
- **Net new this week:** +3 deals ($175K)
- **Lost this week:** 0 | **Won this week:** 0

## Forecast by Confidence
| Bucket | Amount | Deals |
|--------|--------|-------|
| Committed | $490K | Acme Corp + CloudFirst |
| Best case | $865K | + NexaHealth + Atlas |
| Upside | $1.34M | + Meridian + Summit |

## Stalled Deals (Action Required)
1. **Meridian Corp** ($220K) — 12 days, no activity
   → VP-to-VP outreach, Sarah to schedule exec call
2. **Pinnacle Tech** ($65K) — 15 days, close date pushed 3x
   → Re-qualify — may not be a real opportunity
3. **Atlas Financial** ($95K) — competitor mentioned
   → Send competitive battle card, schedule value demo

## Rep Coaching Notes
- **Sarah K:** Strong pipeline ($765K), close Acme this week
- **Mike R:** Needs help with Atlas — prep competitive response
- **Jordan L:** Pinnacle stall — coach on qualification criteria

## Top 3 Actions This Week
1. Close Acme Corp — contract in redline, push for signature
2. Meridian rescue — exec outreach before deal goes cold
3. Pinnacle qualification — go/no-go decision by Friday
`,
  },

  // ── P8: Compliance (1 output) ─────────────────────────────────────
  {
    originalName: "compliance-audit-report.md",
    projectIndex: 7,
    taskIndex: 42,
    direction: "output",
    category: "report",
    content: `# Monthly Compliance Audit Report — March 2026
*Generated by Compliance Audit Workflow*

## Executive Summary
- **Overall posture:** GREEN (improving)
- **Controls satisfied:** 14 of 16 (87.5%)
- **Trend:** +1 control vs February (81.25%)

## Audit Scope
| Metric | Value |
|--------|-------|
| Period | March 1-31, 2026 |
| Governed executions | 1,247 |
| Permission requests | 89 (82 approved, 7 denied) |
| Tool invocations | 3,420 |

## Control Effectiveness
| Control | Status |
|---------|--------|
| CC1.1 - Access Control | PASS |
| CC1.2 - Authentication | PASS |
| CC2.1 - Risk Assessment | PASS |
| CC3.1 - Change Management | PASS |
| CC5.1 - Monitoring | PASS |
| CC6.1 - Logical Access | **PARTIAL** (3 Bash auto-approves) |
| CC7.2 - Incident Response | **PARTIAL** (budget breach alerts) |

## Gap Analysis
1. **CC6.1** — 3 Bash commands auto-approved that should require review
   - Severity: Medium
   - Remediation: Update auto-approve policy by April 15
2. **CC7.2** — Heartbeat budget exceeded twice without notification
   - Severity: Low
   - Remediation: Add budget breach alert by April 10

## Month-over-Month Trend
| Month | Score | Gaps | Posture |
|-------|-------|------|---------|
| January | 75.0% | 4 | YELLOW |
| February | 81.25% | 3 | YELLOW |
| March | 87.5% | 2 | GREEN |
| **Target (June)** | **93.75%** | **1 max** | **GREEN** |
`,
  },
];

/**
 * Write document files to disk and return seed records.
 * All documents are markdown — no async binary generation needed.
 */
export async function createDocuments(
  projectIds: string[],
  taskIds: string[]
): Promise<DocumentSeed[]> {
  mkdirSync(uploadsDir, { recursive: true });

  const results: DocumentSeed[] = [];

  for (const def of DOCUMENTS) {
    const id = crypto.randomUUID();
    const filename = `${id}.md`;
    const storagePath = join(uploadsDir, filename);

    const buf = Buffer.from(def.content, "utf-8");
    writeFileSync(storagePath, buf);

    const taskId = taskIds[def.taskIndex];
    const projectId = projectIds[def.projectIndex];

    results.push({
      id,
      taskId,
      projectId,
      filename,
      originalName: def.originalName,
      mimeType: "text/markdown",
      size: buf.length,
      storagePath,
      direction: def.direction,
      category: def.category,
      status: "uploaded" as const,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
  }

  return results;
}
